#' @title Balanced estimation of centred spatial covariance for stationary RACS
#' @export ccvcs  ccvcs.cvchat
#' @description 
#' This function estimate the centred covariance of a stationary RACS. 
#' A variety of balanced, partially balanced and classical estimates are available.
#' @author{Kassel Liam Hingee}

#' @param xi An observation of the RACS of interest. It can be in \pkg{spatstat}'s \code{owin} or \code{im} format. If \code{xi} is in \code{im} format then it is assumed that the pixels will be valued 1 (for foreground), 0 (for background) and NA for unobserved.
#' If \code{xi} is in \code{owin} format take care to consider what exactly the observation window is (if none is supplied then it will be assumed that the observation window is the smallest rectangle enclosing \code{xi}).
#' @param obswin The observation window in \code{owin} format. If it isn't included and \code{xi} is an \code{owin} object then \code{obswin} is taken to be the smallest rectangle enclosing \code{xi}. If \code{xi} is a \code{im} object than \code{obswin} is all the non-NA pixels in \code{xi}.
#' @param setcov_boundarythresh Any vector \eqn{v} such that set covariance of the observation window
#'  is smaller than this threshold is given a covariance of NA to avoid instabilities caused by dividing by very small areas, 
#' @param phat The classical estimate of coverage probability,
#'  which is the observed area in \code{xi} divided by the total area of the observation window.
#'  See \code{coverageprob} for more information.
#' @param cvchat The classical estimate of covariance in \code{im} format. Typically created with \code{tradcovarest}.
#' @param cpp1 Picka's coverage probability estimate in \code{im} format. Typically generated by \code{cppicka} - see help for \code{cppicka} for more information.
#' @param modifications A list of strings specifying desired modifications or functions to apply to cvchat, cpp1 and phat.
#'  modifications = "all" will select all inbuilt modifications. See details. 

#' @return A named imlist of \pkg{SpatStat} \code{im} objects containing the centred covariance estimates from the different modifications.
#'  
#' 


#' @keywords spatial nonparametric

#' @details 
#' Computes centred covariance using \code{racscovariance}. See help file for \code{racscovariance} for available modifications.

#' @examples
#' xi <- heather$coarse
#' obswin <- Frame(xi)
#' ccvcs(xi, obswin, modifications = "all")

ccvcs <- function(xi, obswin = NULL,
        setcov_boundarythresh = NULL,
        modifications = "all"){
  cvchat <- tradcovarest(xi, obswin, setcov_boundarythresh = setcov_boundarythresh)
  cpp1 <- cppicka(xi, obswin, setcov_boundarythresh = setcov_boundarythresh)
  phat <- coverageprob(xi, obswin)
  
  ccvchats <- ccvcs.cvchat(cvchat, cpp1, phat, modifications = modifications) 
  
  return(ccvchats)
}

#' @describeIn ccvcs Estimates centred covariance using supplied classical covariance estimate (from \code{tradcovarest}),
#'  Picka's coverage probability estimator and coverage probability.
ccvcs.cvchat <- function(cvchat, cpp1 = NULL, phat = NULL,
        setcov_boundarythresh = NULL,
        modifications = "all"){
  
  cvchats <- racscovariance.cvchat(cvchat, cpp1, phat, modifications = modifications) 
  
  return(cvchats - phat^2)
}
