#' @title Simulation of Boolean Model of Deterministic Rectangles
#' @export rbdr  bdrcoverageprob  bdrcovar
#' 
#' @description Functions for simulating a Boolean model with grains that are deterministic rectangles.
#' A Boolean model is a two stage model, first the locations (called germs) of grains are randomly distributed according to a Poisson point process, then a random grain is placed on each germ independently.
#' A thorough introduction can be found in [3].
#' Also described in this help file are functions for calculating the true coverage probability and covariance.
#' 
#' @param lambda Intensity of the germ process (which is a Poisson point process)
#' @param grain Recantangle object specifying the grain
#' @param win The window to simulate in (an owin object)
#' @param seed Optional input (default in NULL). Is an integer passed to \code{\link{base}{set.seed}}. Used to reproduce patterns exactly.
#' @param xy A raster object that specifies the pixel coordinates of the desired covariance image. In the same vein and as.mask in spatstat.

#' @return 
#' Depends on the function used (see Functions section).

#' @section WARNING:
#' The returned object of \code{rbdr} is only the contents of Xi and thus could be much smaller than the window (e.g. when the simulated set is empty).
#' 
#' 
#' @examples 
#' grain <- owin(xrange = c(-5, 5), yrange = c(-5, 5))
#' win <- owin(xrange = c(0, 100), c(0, 100))
#' lambda <- 4.2064E-3
#' xi <- rbdr(lambda, grain, win)
#' plot(xi, col = "black")
#' plot(win, add = TRUE)
#' 
#' #calculate theoretical values of the model
#' truecoverageprob <- bdrcoverageprob(lambda, grain)
#' xy <- as.mask(dilationAny(win, win), eps = c(1, 1))
#' truecovariance <- bdrcovar(lambda, grain, xy)
#' plot(truecovariance)
#' 
#' ######################
#' #test
#' grain <- owin(xrange = c(-5, 5), yrange = c(-5, 5))
#' win <- owin(xrange = c(0, 200), c(0, 200))
#' lambda <- 4.2064E-3
#' xi <- rbdr(lambda, grain, win)
#' plot(xi, col = "black")
#' plot(win, add = TRUE)
#' 
#' #calculate theoretical values of the model
#' truep <- bdrcoverageprob(lambda, grain)
#' xy <- as.mask(dilationAny(win, win), eps = c(0.1, 0.1))
#'  #eps of 1 (a 10 grain width) is too large! eps of 0.1
#' truecvc <- bdrcovar(lambda, grain, xy)
#' 
#' #estimate values should be close for a large window
#' phat <- coverageprob(xi, win)
#' truep - phat
#' cvchat <- balancedracscovariances(as.mask(xi, eps = c(0.1, 0.1)), obswin = win, modifications = list("pickaadd"))[[1]]
#' plot.solist(solist(
#'   True = truecvc,
#'   PickaEstimate = cvchat), equal.ribbon = TRUE, main = "Covariance: True and Estimate")
#' plot(eval.im(truecvc - cvchat), main = "Difference Between Estimate and True")
#' truecvc.iso <- rotmean(truecvc[disc(radius = 50), drop = FALSE], padzero = FALSE)
#' cvchat.iso <- rotmean(cvchat[disc(radius = 50)], padzero = FALSE)
#' plot(truecvc.iso)
#' plot(cvchat.iso, col = "red", add = TRUE)
#' plot(truecvc.iso, xlim = c(0, 20))
#' plot(cvchat.iso, col = "red", add = TRUE)

#' @references 
#' [3] Chiu, S.N., Stoyan, D., Kendall, W.S. and Mecke, J. (2013) Stochastic Geometry and Its Applications, 3rd ed. Chichester, United Kingdom: John Wiley & Sons.
#' @keywords spatial datagen

#' @describeIn rbdr Returns an \code{owin} that is a set generated by simulating a deterministic rectangle Boolean
#'  model with a specified intensity and rectangular grain.
#'  The window information is not contained in this object.
#'  If the simulated set is empty then an empty \code{owin} object is returned.
#' The point process of germs is generated using spatstat's \code{\link[spatstat]{rpoispp}}.
rbdr <- function(lambda, grain, win, seed = NULL){
  grainlib <- solist(grain)
  bufferdist <- 1.1 *
    (diameter.owin(grain)/2 + sqrt(sum(unlist(centroid.owin(grain))^2)))
  
  if (!missing(seed)){set.seed(seed)}
  pp <- rpoispp(lambda = lambda, win = dilation.owin(win, bufferdist), nsim = 1, drop = TRUE) 
  if (pp$n == 0 ){return( setminus.owin(square(r = 1), square(r = 1)) )}
  xibuffer <- placegrainsfromlib(pp, grainlib, w = win)
  xi <- intersect.owin(xibuffer, win)
  return(xi)
}

#' @describeIn rbdr Returns the true coverage probability given the intensity and grain.
bdrcoverageprob  <- function(lambda, grain){
  return (1 - exp(- lambda * area.owin(grain)))
}


#theoretical set covariance of a rectangle
#grain is an owin rectangle object
#v1, v2 is shift vector list for x and y directions equally, or vec is list with x and y components
setcov.vec.rect <- function(rectang, v1 = NULL, v2 = NULL, vec = NULL){
  stopifnot(is.rectangle(rectang))
  if (!is.null(vec)){
    v1 <- vec$x
    v2 <- vec$y
  }
  xwidth <- pmax(0, (rectang$xrange[[2]] - rectang$xrange[[1]]) - abs(v1))
  ywidth <- pmax(0, (rectang$yrange[[2]] - rectang$yrange[[1]]) - abs(v2))
  return(xwidth * ywidth)
}

#' @describeIn rbdr Returns an image of the covariance as calculated from disc radius and intensity.
bdrcovar <- function(lambda, grain, xy){
  expectedsetcovariance <- as.im.funxy(function(x, y) setcov.vec.rect(grain, v1 = x, v2 = y)  ,
  W = Frame(xy), xy = xy)
  p <- bdrcoverageprob(lambda, grain)
  covariance <- eval.im(2 * p - 1 + (1 - p ) ^ 2 * exp(lambda * expectedsetcovariance))
  return(covariance)
}
